# steps:
#   - label: test
#     command: 
#       - ansible-playbook build-env-rails 
#       - budnle install
#       - run db prepare
#       - rake test
#       - cucumber
#       - ansible-playbook destroy-env-rails 


steps:
 - command: run test
    plugins:
      docker-compose#v1.3.2:
        run: ruby